// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRhEqDpKHJupSSlm_E3yjNkaVXB4eVP9s',
    appId: '1:990149127253:web:7fcb374ac1d9b985c0f8dc',
    messagingSenderId: '990149127253',
    projectId: 'to-do-ap-7b429',
    authDomain: 'to-do-ap-7b429.firebaseapp.com',
    storageBucket: 'to-do-ap-7b429.firebasestorage.app',
    measurementId: 'G-7V78NV17P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRYYrPjBOwz3AVf5HRONUUFh3LMZb3t3s',
    appId: '1:990149127253:android:dd38b99ee556fa90c0f8dc',
    messagingSenderId: '990149127253',
    projectId: 'to-do-ap-7b429',
    storageBucket: 'to-do-ap-7b429.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw6qHZvrRS5Xg8g94bdm7oA_q5AO5qMy0',
    appId: '1:990149127253:ios:5ff7b17745019dd5c0f8dc',
    messagingSenderId: '990149127253',
    projectId: 'to-do-ap-7b429',
    storageBucket: 'to-do-ap-7b429.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );
}
